version: '3.8'
services:
  db:
    image: postgres
    container_name: trading_app_db
    environment:
      - POSTGRES_USER=trading-backtester
      - POSTGRES_PASSWORD=trading-backtester
      - POSTGRES_DB=trading-backtester
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5433
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - trading-backtester-db:/var/lib/postgresql/data

  maildev:
    image: maildev/maildev
    container_name: trading_app_maildev
    ports:
      - '3002:1025'
      - '3003:1080'
    depends_on:
      - db
    restart: unless-stopped

volumes:
  trading-backtester-db:
